# Generated by Django 2.2.1 on 2019-06-30 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('totalPts', models.IntegerField(default=0)),
                ('badge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Badge')),
            ],
        ),
        migrations.AlterField(
            model_name='statistics',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Player'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
