# Generated by Django 2.1.15 on 2020-06-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20190630_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='totalQuestionsCreated',
            field=models.IntegerField(default=0),
        ),
    ]
